#cloud-config
ssh_pwauth: true
chpasswd:
  list: |
    root:${root_password}
  expire: false
disable_root: false

hostname: ${vm_hostname}

apt:
  preserve_sources_list: false
  sources_list: |
        Types: deb
        URIs: https://mirrors.tuna.tsinghua.edu.cn/ubuntu
        Suites: jammy jammy-updates jammy-backports
        Components: main restricted universe multiverse
        Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

        Types: deb
        URIs: http://security.ubuntu.com/ubuntu/
        Suites: jammy-security
        Components: main restricted universe multiverse
        Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
packages:
  - openssh-server
  - qemu-guest-agent

runcmd:
  - [ sh, -c, 'rm -f /etc/ssh/sshd_config.d/*.conf' ]
  - [ sh, -c, 'echo "PermitRootLogin yes" > /etc/ssh/sshd_config.d/99-root-login.conf' ]
  - [ sh, -c, 'echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config.d/99-root-login.conf' ]
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - systemctl restart sshd

ssh_authorized_keys:
  - ${ssh_keys}
